---
# copied from https://github.com/opendatahub-io/odh-manifests/blob/master/jupyterhub/notebook-images/overlays/additional/elyra-notebook-imagestream.yaml
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: s2i-lab-elyra
  labels:
    opendatahub.io/notebook-image: "true"
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: 'true'
    byoni: 'true'
  annotations:
    opendatahub.io/notebook-image-name: "Elyra Notebook Image"
    opendatahub.io/notebook-image-url: "https://github.com/thoth-station/s2i-lab-elyra"
    opendatahub.io/notebook-image-desc: "Jupyter notebook image with Elyra-AI installed"
spec:
  lookupPolicy:
    local: true
  tags:
  - name: "v0.0.9"
    annotations:
      opendatahub.io/notebook-software: '[{"name":"BYO Notebook Image - Python","version":"v3.8.6"}]'
      opendatahub.io/notebook-python-dependencies: '[{"name":"elyra","version":"2.2.4"}]'
      openshift.io/imported-from: quay.io/thoth-station/s2i-lab-elyra
    from:
      kind: DockerImage
      name: quay.io/thoth-station/s2i-lab-elyra:v0.0.9
    referencePolicy:
      type: Source