---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: r-notebook
  namespace: redhat-ods-applications
  labels:
    opendatahub.io/notebook-image: 'true'
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: 'true'
    byoni: 'true'
  annotations:
    opendatahub.io/notebook-image-name: "R Notebook"
    opendatahub.io/notebook-image-desc: "Jupyter notebook image with a set of data science libraries and R"
    opendatahub.io/notebook-image-order: '200'
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "v0.0.2"
      annotations:
        opendatahub.io/notebook-python-dependencies: '[{"name":"Boto3","version":"1.17.11"},{"name":"Kafka-Python","version":"2.0.2"},{"name":"Matplotlib","version":"3.1.3"},{"name":"Numpy","version":"1.20.3"},{"name":"Pandas","version":"1.2.4"},{"name":"Scipy","version":"1.6.3"}]'
        opendatahub.io/notebook-software: '[{"name":"BYO Notebook Image - Boto3","version":"1.17.11"}]'
      from:
        kind: DockerImage
        name: quay.io/guimou/datascience-full-notebook:0.0.2
      referencePolicy:
        type: Source
